spring:
  application:
    name: Murasaki Languages

  data:
    mongodb:
      host: localhost
      port: 27017
      database: murasaki-languages
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000

murasakilanguages:
  security:
    secret: ${SECRET}