spring:
  application:
    name: Murasaki Languages

  data:
    mongodb:
      host: localhost
      port: 27017
      database: murasaki-languages
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: murasakilanguages@gmail.com
    password: ${MAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
    chat:
      model: gpt-4.1-mini

murasakilanguages:
  security:
    secret: ${SECRET}

