name: Build and deploy of MurasakiLanguage

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Build Project
        run: mvn clean install
